dubbo:
  application:
    name: ego-manage
  registry:
    address: zookeeper://192.168.3.10:2181

server:
  port: 80
#SpringMVC视图解析器
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
